// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package user

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID              int32            `db:"id" json:"id"`
	UserID          *int32           `db:"user_id" json:"user_id"`
	ProductID       *int32           `db:"product_id" json:"product_id"`
	Status          string           `db:"status" json:"status"`
	Data            []byte           `db:"data" json:"data"`
	CalculatedPrice pgtype.Numeric   `db:"calculated_price" json:"calculated_price"`
	ManagerID       *int32           `db:"manager_id" json:"manager_id"`
	RejectionReason *string          `db:"rejection_reason" json:"rejection_reason"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type ApplicationComment struct {
	ID            int32            `db:"id" json:"id"`
	ApplicationID *int32           `db:"application_id" json:"application_id"`
	UserID        *int32           `db:"user_id" json:"user_id"`
	Comment       string           `db:"comment" json:"comment"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type ApplicationStatusHistory struct {
	ID            int32            `db:"id" json:"id"`
	ApplicationID *int32           `db:"application_id" json:"application_id"`
	OldStatus     *string          `db:"old_status" json:"old_status"`
	NewStatus     string           `db:"new_status" json:"new_status"`
	ChangedBy     *int32           `db:"changed_by" json:"changed_by"`
	Comment       *string          `db:"comment" json:"comment"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Payment struct {
	ID            int32            `db:"id" json:"id"`
	PolicyID      *int32           `db:"policy_id" json:"policy_id"`
	UserID        *int32           `db:"user_id" json:"user_id"`
	Amount        pgtype.Numeric   `db:"amount" json:"amount"`
	Status        string           `db:"status" json:"status"`
	PaymentMethod *string          `db:"payment_method" json:"payment_method"`
	TransactionID *string          `db:"transaction_id" json:"transaction_id"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Policy struct {
	ID             int32            `db:"id" json:"id"`
	PolicyNumber   string           `db:"policy_number" json:"policy_number"`
	ApplicationID  *int32           `db:"application_id" json:"application_id"`
	UserID         *int32           `db:"user_id" json:"user_id"`
	ProductID      *int32           `db:"product_id" json:"product_id"`
	Status         string           `db:"status" json:"status"`
	StartDate      pgtype.Date      `db:"start_date" json:"start_date"`
	EndDate        pgtype.Date      `db:"end_date" json:"end_date"`
	CoverageAmount pgtype.Numeric   `db:"coverage_amount" json:"coverage_amount"`
	Premium        pgtype.Numeric   `db:"premium" json:"premium"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Product struct {
	ID          int32          `db:"id" json:"id"`
	Type        string         `db:"type" json:"type"`
	Name        string         `db:"name" json:"name"`
	Description *string        `db:"description" json:"description"`
	BasePrice   pgtype.Numeric `db:"base_price" json:"base_price"`
	IsActive    *bool          `db:"is_active" json:"is_active"`
}

type RefreshToken struct {
	ID        int32            `db:"id" json:"id"`
	UserID    *int32           `db:"user_id" json:"user_id"`
	Token     string           `db:"token" json:"token"`
	ExpiresAt pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	DeletedAt pgtype.Timestamp `db:"deleted_at" json:"deleted_at"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type User struct {
	ID           int32            `db:"id" json:"id"`
	Email        string           `db:"email" json:"email"`
	PasswordHash string           `db:"password_hash" json:"password_hash"`
	FullName     string           `db:"full_name" json:"full_name"`
	Phone        *string          `db:"phone" json:"phone"`
	BirthDate    pgtype.Date      `db:"birth_date" json:"birth_date"`
	Address      *string          `db:"address" json:"address"`
	Role         string           `db:"role" json:"role"`
	IsActive     *bool            `db:"is_active" json:"is_active"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}
