// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package user

import (
	"context"
)

type Querier interface {
	CreateToken(ctx context.Context, arg *CreateTokenParams) error
	CreateUser(ctx context.Context, arg *CreateUserParams) (*CreateUserRow, error)
	DeleteToken(ctx context.Context, arg *DeleteTokenParams) error
	GetByEmail(ctx context.Context, arg *GetByEmailParams) (*GetByEmailRow, error)
}

var _ Querier = (*Queries)(nil)
