// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package user

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserApplications = `-- name: CountUserApplications :one
SELECT COUNT(*) AS total
FROM applications
WHERE user_id = $1 AND status = $2
`

type CountUserApplicationsParams struct {
	UserID *int32 `db:"user_id" json:"user_id"`
	Status string `db:"status" json:"status"`
}

func (q *Queries) CountUserApplications(ctx context.Context, arg *CountUserApplicationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserApplications, arg.UserID, arg.Status)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countUserPolicies = `-- name: CountUserPolicies :one
SELECT COUNT(*) AS total
FROM policies
WHERE user_id = $1 AND status = $2
`

type CountUserPoliciesParams struct {
	UserID *int32 `db:"user_id" json:"user_id"`
	Status string `db:"status" json:"status"`
}

func (q *Queries) CountUserPolicies(ctx context.Context, arg *CountUserPoliciesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserPolicies, arg.UserID, arg.Status)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createToken = `-- name: CreateToken :exec
INSERT INTO refresh_tokens (user_id, token, expires_at)
VALUES ($1, $2, $3)
`

type CreateTokenParams struct {
	UserID    *int32           `db:"user_id" json:"user_id"`
	Token     string           `db:"token" json:"token"`
	ExpiresAt pgtype.Timestamp `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateToken(ctx context.Context, arg *CreateTokenParams) error {
	_, err := q.db.Exec(ctx, createToken, arg.UserID, arg.Token, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, full_name, phone, birth_date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, full_name
`

type CreateUserParams struct {
	Email        string      `db:"email" json:"email"`
	PasswordHash string      `db:"password_hash" json:"password_hash"`
	FullName     string      `db:"full_name" json:"full_name"`
	Phone        *string     `db:"phone" json:"phone"`
	BirthDate    pgtype.Date `db:"birth_date" json:"birth_date"`
}

type CreateUserRow struct {
	ID       int32  `db:"id" json:"id"`
	Email    string `db:"email" json:"email"`
	FullName string `db:"full_name" json:"full_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (*CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Phone,
		arg.BirthDate,
	)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email, &i.FullName)
	return &i, err
}

const deleteToken = `-- name: DeleteToken :exec
UPDATE refresh_tokens
SET deleted_at = NOW()
WHERE token = $1
`

type DeleteTokenParams struct {
	Token string `db:"token" json:"token"`
}

func (q *Queries) DeleteToken(ctx context.Context, arg *DeleteTokenParams) error {
	_, err := q.db.Exec(ctx, deleteToken, arg.Token)
	return err
}

const getByEmail = `-- name: GetByEmail :one
SELECT id, email, role, password_hash
FROM users
WHERE email = $1
`

type GetByEmailParams struct {
	Email string `db:"email" json:"email"`
}

type GetByEmailRow struct {
	ID           int32  `db:"id" json:"id"`
	Email        string `db:"email" json:"email"`
	Role         string `db:"role" json:"role"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

func (q *Queries) GetByEmail(ctx context.Context, arg *GetByEmailParams) (*GetByEmailRow, error) {
	row := q.db.QueryRow(ctx, getByEmail, arg.Email)
	var i GetByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.PasswordHash,
	)
	return &i, err
}

const getByID = `-- name: GetByID :one
SELECT email, full_name, phone, birth_date, address, role
FROM users
WHERE id = $1
`

type GetByIDParams struct {
	ID int32 `db:"id" json:"id"`
}

type GetByIDRow struct {
	Email     string      `db:"email" json:"email"`
	FullName  string      `db:"full_name" json:"full_name"`
	Phone     *string     `db:"phone" json:"phone"`
	BirthDate pgtype.Date `db:"birth_date" json:"birth_date"`
	Address   *string     `db:"address" json:"address"`
	Role      string      `db:"role" json:"role"`
}

func (q *Queries) GetByID(ctx context.Context, arg *GetByIDParams) (*GetByIDRow, error) {
	row := q.db.QueryRow(ctx, getByID, arg.ID)
	var i GetByIDRow
	err := row.Scan(
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.BirthDate,
		&i.Address,
		&i.Role,
	)
	return &i, err
}

const getRecentUserActivity = `-- name: GetRecentUserActivity :many
SELECT a.id, 'application' AS type, a.status, a.created_at, p.type AS product_type, a.calculated_price
FROM applications a
         JOIN products p ON a.product_id = p.id
WHERE a.user_id = $1
UNION ALL
SELECT p.id, 'policy' AS type, p.status, p.created_at, pr.type AS product_type, NULL AS calculated_price
FROM policies p
         JOIN products pr ON p.product_id = pr.id
WHERE p.user_id = $1
ORDER BY created_at DESC
    LIMIT $2
`

type GetRecentUserActivityParams struct {
	UserID *int32 `db:"user_id" json:"user_id"`
	Limit  int32  `db:"limit" json:"limit"`
}

type GetRecentUserActivityRow struct {
	ID              int32            `db:"id" json:"id"`
	Type            string           `db:"type" json:"type"`
	Status          string           `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
	ProductType     string           `db:"product_type" json:"product_type"`
	CalculatedPrice pgtype.Numeric   `db:"calculated_price" json:"calculated_price"`
}

func (q *Queries) GetRecentUserActivity(ctx context.Context, arg *GetRecentUserActivityParams) ([]*GetRecentUserActivityRow, error) {
	rows, err := q.db.Query(ctx, getRecentUserActivity, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetRecentUserActivityRow
	for rows.Next() {
		var i GetRecentUserActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.CreatedAt,
			&i.ProductType,
			&i.CalculatedPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumUserPoliciesCoverage = `-- name: SumUserPoliciesCoverage :one
SELECT COALESCE(SUM(coverage_amount),0) AS total
FROM policies
WHERE user_id = $1 AND status = $2
`

type SumUserPoliciesCoverageParams struct {
	UserID *int32 `db:"user_id" json:"user_id"`
	Status string `db:"status" json:"status"`
}

func (q *Queries) SumUserPoliciesCoverage(ctx context.Context, arg *SumUserPoliciesCoverageParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, sumUserPoliciesCoverage, arg.UserID, arg.Status)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET (full_name, email, address) = ($2, $3, $4)
WHERE id = $1
RETURNING email, full_name, phone, birth_date, address, role
`

type UpdateUserParams struct {
	ID       int32   `db:"id" json:"id"`
	FullName string  `db:"full_name" json:"full_name"`
	Email    string  `db:"email" json:"email"`
	Address  *string `db:"address" json:"address"`
}

type UpdateUserRow struct {
	Email     string      `db:"email" json:"email"`
	FullName  string      `db:"full_name" json:"full_name"`
	Phone     *string     `db:"phone" json:"phone"`
	BirthDate pgtype.Date `db:"birth_date" json:"birth_date"`
	Address   *string     `db:"address" json:"address"`
	Role      string      `db:"role" json:"role"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg *UpdateUserParams) (*UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.Address,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.BirthDate,
		&i.Address,
		&i.Role,
	)
	return &i, err
}
