// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: policies.sql

package policy

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPolicies = `-- name: GetPolicies :many
SELECT
    p.id,
    p.policy_number,
    pr.type AS product_type,
    p.status,
    p.start_date,
    p.end_date,
    p.coverage_amount,
    p.premium
FROM policies p
         JOIN products pr ON p.product_id = pr.id
WHERE p.user_id = $1
  AND ($2::text IS NULL OR p.status = $2)
ORDER BY p.created_at DESC
    LIMIT $3 OFFSET $4
`

type GetPoliciesParams struct {
	UserID  *int32 `db:"user_id" json:"user_id"`
	Column2 string `db:"column_2" json:"column_2"`
	Limit   int32  `db:"limit" json:"limit"`
	Offset  int32  `db:"offset" json:"offset"`
}

type GetPoliciesRow struct {
	ID             int32          `db:"id" json:"id"`
	PolicyNumber   string         `db:"policy_number" json:"policy_number"`
	ProductType    string         `db:"product_type" json:"product_type"`
	Status         string         `db:"status" json:"status"`
	StartDate      pgtype.Date    `db:"start_date" json:"start_date"`
	EndDate        pgtype.Date    `db:"end_date" json:"end_date"`
	CoverageAmount pgtype.Numeric `db:"coverage_amount" json:"coverage_amount"`
	Premium        pgtype.Numeric `db:"premium" json:"premium"`
}

func (q *Queries) GetPolicies(ctx context.Context, arg *GetPoliciesParams) ([]*GetPoliciesRow, error) {
	rows, err := q.db.Query(ctx, getPolicies,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetPoliciesRow
	for rows.Next() {
		var i GetPoliciesRow
		if err := rows.Scan(
			&i.ID,
			&i.PolicyNumber,
			&i.ProductType,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CoverageAmount,
			&i.Premium,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPoliciesCount = `-- name: GetPoliciesCount :one
SELECT COUNT(*) AS total
FROM policies
WHERE user_id = $1
  AND ($2::text IS NULL OR status = $2)
`

type GetPoliciesCountParams struct {
	UserID  *int32 `db:"user_id" json:"user_id"`
	Column2 string `db:"column_2" json:"column_2"`
}

func (q *Queries) GetPoliciesCount(ctx context.Context, arg *GetPoliciesCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getPoliciesCount, arg.UserID, arg.Column2)
	var total int64
	err := row.Scan(&total)
	return total, err
}
