// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package policy

import (
	"context"
)

type Querier interface {
	GetAllPolicies(ctx context.Context, arg *GetAllPoliciesParams) ([]*GetAllPoliciesRow, error)
	GetPolicies(ctx context.Context, arg *GetPoliciesParams) ([]*GetPoliciesRow, error)
	GetPoliciesCount(ctx context.Context, arg *GetPoliciesCountParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
