// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package application

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications(user_id, product_id, data, calculated_price, manager_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, status, calculated_price, created_at
`

type CreateApplicationParams struct {
	UserID          *int32         `db:"user_id" json:"user_id"`
	ProductID       *int32         `db:"product_id" json:"product_id"`
	Data            []byte         `db:"data" json:"data"`
	CalculatedPrice pgtype.Numeric `db:"calculated_price" json:"calculated_price"`
	ManagerID       *int32         `db:"manager_id" json:"manager_id"`
}

type CreateApplicationRow struct {
	ID              int32            `db:"id" json:"id"`
	Status          string           `db:"status" json:"status"`
	CalculatedPrice pgtype.Numeric   `db:"calculated_price" json:"calculated_price"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg *CreateApplicationParams) (*CreateApplicationRow, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.UserID,
		arg.ProductID,
		arg.Data,
		arg.CalculatedPrice,
		arg.ManagerID,
	)
	var i CreateApplicationRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CalculatedPrice,
		&i.CreatedAt,
	)
	return &i, err
}
