// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package application

import (
	"context"
)

type Querier interface {
	CreateApplication(ctx context.Context, arg *CreateApplicationParams) (*CreateApplicationRow, error)
	GetApplicationByID(ctx context.Context, arg *GetApplicationByIDParams) (*GetApplicationByIDRow, error)
	GetApplicationStatusHistory(ctx context.Context, arg *GetApplicationStatusHistoryParams) ([]*GetApplicationStatusHistoryRow, error)
	GetApplications(ctx context.Context, arg *GetApplicationsParams) ([]*GetApplicationsRow, error)
	GetApplicationsCount(ctx context.Context, arg *GetApplicationsCountParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
