// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package application

import (
	"context"
)

type Querier interface {
	CreateApplication(ctx context.Context, arg *CreateApplicationParams) (*CreateApplicationRow, error)
}

var _ Querier = (*Queries)(nil)
