// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package application

import (
	"context"
)

type Querier interface {
	CreateApplication(ctx context.Context, arg *CreateApplicationParams) (*CreateApplicationRow, error)
	CreateApplicationComment(ctx context.Context, arg *CreateApplicationCommentParams) error
	CreateApplicationCommentt(ctx context.Context, arg *CreateApplicationCommenttParams) (*CreateApplicationCommenttRow, error)
	GetApplicationByID(ctx context.Context, arg *GetApplicationByIDParams) (*GetApplicationByIDRow, error)
	GetApplicationComments(ctx context.Context, arg *GetApplicationCommentsParams) ([]*GetApplicationCommentsRow, error)
	GetApplicationStatusHistory(ctx context.Context, arg *GetApplicationStatusHistoryParams) ([]*GetApplicationStatusHistoryRow, error)
	GetApplications(ctx context.Context, arg *GetApplicationsParams) ([]*GetApplicationsRow, error)
	GetApplicationsConversion(ctx context.Context, arg *GetApplicationsConversionParams) (*GetApplicationsConversionRow, error)
	GetApplicationsCount(ctx context.Context, arg *GetApplicationsCountParams) (int64, error)
	GetApplicationsCountByStatus(ctx context.Context, arg *GetApplicationsCountByStatusParams) ([]*GetApplicationsCountByStatusRow, error)
	GetApplicationsCountByType(ctx context.Context, arg *GetApplicationsCountByTypeParams) ([]*GetApplicationsCountByTypeRow, error)
	GetManagerApplicationByID(ctx context.Context, arg *GetManagerApplicationByIDParams) (*GetManagerApplicationByIDRow, error)
	GetManagerApplications(ctx context.Context, arg *GetManagerApplicationsParams) ([]*GetManagerApplicationsRow, error)
	GetManagerApplicationsCount(ctx context.Context, arg *GetManagerApplicationsCountParams) (int64, error)
	GetUserByID(ctx context.Context, arg *GetUserByIDParams) (*GetUserByIDRow, error)
	UpdateApplicationStatus(ctx context.Context, arg *UpdateApplicationStatusParams) (*UpdateApplicationStatusRow, error)
}

var _ Querier = (*Queries)(nil)
