// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package product

import (
	"context"
)

type Querier interface {
	GetProductWithType(ctx context.Context, arg *GetProductWithTypeParams) ([]*GetProductWithTypeRow, error)
	GetProducts(ctx context.Context) ([]*GetProductsRow, error)
}

var _ Querier = (*Queries)(nil)
